language: node_js
node_js:
  - '6'
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - npm config set spin false
  - npm install -g npm@^5
script:
  - yarn test-ci
  - yarn build
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "eg8+OsDHhkmV+L3YPVzTZdGetCp8TDjgIlonqSzsrMCoAh1jIvJQyhpKLaXAPK9k9CxRsLlE3BD+snmTKpDVmw3VCfL2yM5V2kgNRg7NNgksS9Dqzfp0cRPsemVoSCgJwTNh6G6YduP5qcyiMEQz5WJ0rTmi6/2qb5fmwNskg+BS+XPRQCldv8iJ0/FvlsZ1eNrDpKYIN6k+lXCQMoGUWkus4+AMzcPWvfzwqcw+H/bIkE6eGjEUTtrrX6HetjMeCo60x/NRoFA2v4t3z0aBS2I2bce3yO9lUPoefMkMzOQ2lvpEd38eAnzmwdP635Y7SJvkqSt5jjrGY1Ilab09xpSwgcDp7Zm6RtAk1xCP7VtIEDjyzGH0r3H20EkNnwbwLKrxaAYRTQujvsXnZwPy2b92iIWiDLAx6lG2PFvsVN4rncTypwgx1Gd9yfO/fC9Cj2oeX/N64YGcMX6C9FqPCkhyfxxjWsx/neJE8FcXe604HTpwboNRJz3smZkj8Brzt4dF7lDV8Lt7HsA39O0VU3192Ag+KO3yJwPxoxojcDOVfRiIGrEzi+8C0TAc0Vxy7dah9a1UbM3NAdN1S+4ofKCoqxmwgDcAq7MhrnyOO8uDZF/cI/FmHiJe7VsevpzGtbRVRqETSIThmscbZlKIJTUblgtjE3TNyDMxT/CtYBg="
  file:
    - build/_output/"word-guess-widget.wigt
    - build/_output/"word-guess-widget-build-info.yml
  on:
    tags: true
    repo: ucfopen/"word-guess-materia-widget
notifications:
  email: false
  slack:
   secure: "fPJoucS8xGIApJVtw06z5ExOD4vjnFPdm1Tu8NZrdXG0WDkhUBhMkGOypJL854mboIXr6JT8ocX3qD8bTsq7zhpZYteMUUQuTCwSv/M7dKu8siqzYKPAY53wKAhmRT4q041df93fyggJplSZcfzYQ9Lz+lrjqHYq/sogKfZiNd66igfx6mQ1KQEkTCfmHSzQ7JaITxijp7ShrRKbJdjPzL8yz+dg+lxm9Bnegz3RX+NfgWsaeq0yaelKh2nfRFFRhNbO2AtREvH+IJ4Uk2LyskvKs1gx9IxeDNZe8Ta/3aPq9BR1S1izX6FmdhI1f8awUkE8YlLGdCndXDmT0d1T5rYcFUFj5sICAQbCCIRfMYv+LLgBg/5q9OUIskUVRGzClmOoPLlr3yEnaXMEbD1qyL3F8cR8LybnLM8QCZYWh8dPlUc860j8VROoyjyq86iARWuI1BFGtlbOQ9oxGhRO0cLSxxstIE8knpmDq8xV2Iu8iC1pJN8H0dReGVWTQSO+2mbx0dYAeLW/EhHZg7+LCWiSMzmiSLuzJXOUWBdpQslzXiuLcwL9FobM9hTSiRnzeJ8y+5Gsw37lnbHiKxDE2kPtNPzdsmou4rUTVv2wnvGIaWFPnJAasmdXO7qAHbXcgTSaC20A7nLOfKfDAHgqRlJiMshnzGUamH2zapCFfTg="
